spring:
  profiles: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://geektry.com:5432/test?allowMultiQueries=true
    username: postgres
    password: shangxin
